name: pora
dependencies:
  - jupyter
  - numpy
  - jax
  - matplotlib
  - shapely
  - scipy
  - seaborn
  - pip
  - pytorch
  - tqdm
  - cvxpy
  - pip:
    - gymnasium[box2d]
    - equinox
    - optax
    - opencv-python
    - pyvirtualdisplay
    - torchvision
    - ultralytics