name: pora
dependencies:
  - jupyter
  - numpy
  - jax
  - matplotlib
  - shapely
  - scipy
  - pip
  - pip:
    - gymnasium[box2d]
    - equinox
    - optax
    - opencv-python
    - pyvirtualdisplay